version: "3.8"

services:
  aetherai:
    build:
      context: ./terminal
      dockerfile: Dockerfile
    image: aetherai:local
    container_name: aetherai_cli
    # Mount repository for rapid iteration (bind mount, use with caution on Windows)
    volumes:
      - ./terminal:/app:rw
    tty: true
    stdin_open: true
    environment:
      - PYTHONUNBUFFERED=1
      - TERM=xterm-256color
    # Keep the CLI interactive by default; override the command to run inline scripts
    command: ["python", "main.py"]
    # Optional: map a local port if any HTTP admin API added later
    ports:
      - "8080:8080"
    restart: unless-stopped
