name: Docker Build & Smoke Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          # Build using the Dockerfile located in the terminal/ directory
          docker build -t aetherai:ci -f terminal/Dockerfile terminal

      - name: Run smoke test (aetherai --help)
        run: |
          # Run the installed console script inside the container and show help output
          docker run --rm aetherai:ci aetherai --help
